# packages Loading

In [1]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd

# Get The URl of the sites

In [14]:
url = "https://www.brawlplanet.com/brawlers"
page = requests.get(url)

In [20]:
soup = bs(page.content, "html.parser")

In [26]:
# print(soup.prettify())

# Find all the tables in the soup

In [69]:
tables = soup.find_all( "tbody", attrs= {"divide-y divide-gray-200 dark:divide-gray-800"})
table_0 = tables[0]
brawler_percentage_list = []

for row in table_0.find_all("tr"):
    brawler_name = row.find_all("td")[0].text
    win_rate = row.find_all("td")[1].text
    use_rate = row.find_all("td")[2].text
    win_rate = row.find_all("td")[3].text

    percentage_per_brawler = []
    percentage_per_brawler.extend((brawler_name,win_rate,use_rate,win_rate ))
    brawler_percentage_list.append(percentage_per_brawler)
    #print(brawler_name)
    #win_rate = row.find_al
    #brawler_percentage_table.append(row)

In [102]:
# Create a dataframe 
data = pd.DataFrame(brawler_percentage_list, 
                    columns=["Brawler name",
                            "Wine Rate (%)", 
                            "Use rate (%)", "Starplayer Rate (%)"])


data.head()

  Brawler name Wine Rate (%) Use rate (%) Starplayer Rate (%)
0      Melodie         16.24         2.31               16.24
1       Angelo         21.13         4.03               21.13
2         Bibi         12.11         8.39               12.11
3      Charlie          8.97         1.97                8.97
4         Carl         19.71         1.49               19.71

In [104]:
table_1 = tables[1]
brawler_info_list = []

for row in table_1.find_all("tr"):
    brawler_name = row.find_all("td")[0].text
    health= row.find_all("td")[1].text
    attack = row.find_all("td")[2].text
    attack_range = row.find_all("td")[3].text
    reload_speed = row.find_all("td")[4].text 
    movement = row.find_all("td")[5].text

    info_per_brawler = []
    info_per_brawler.extend((brawler_name,
                             health,attack,attack_range, reload_speed, movement ))
    brawler_info_list.append(info_per_brawler)
## Create a dataframe 
dataset_info = pd.DataFrame(brawler_info_list, columns = ["Brawler name",
                                                          "Level 1 Health", 
                                                          "Level 1 Damage",
                                                          "Attack Range",
                                                          "Reload Speed",
                                                          "Movement"])

dataset_info.head()

,Brawler name,Level 1 Health,Level 1 Damage,Attack Range,Reload Speed,Movement
0,8-Bit,5000,320,10,1.5,580
1,Amber,3200,210,8.33,0.22,720
2,Angelo,3000,220,10,0.1,820
3,Ash,5400,800,4.67,1.4,720
4,Barley,2400,760,7.33,2,720

# Merge Dataset

In [108]:
data_all = pd.merge(data, dataset_info, on= "Brawler name" )
data_all.head()

,Brawler name,Wine Rate (%),Use rate (%),Starplayer Rate (%),Level 1 Health,Level 1 Damage,Attack Range,Reload Speed,Movement
0,Melodie,16.24,2.31,16.24,4100,460,8,1.5,720
1,Angelo,21.13,4.03,21.13,3000,220,10,0.1,820
2,Bibi,12.11,8.39,12.11,4800,1400,3.67,0.8,820
3,Charlie,8.97,1.97,8.97,3300,800,9,0,720
4,Carl,19.71,1.49,19.71,4000,740,8.33,0,720

# Save data

In [113]:
data_all.to_csv("Brawler_name.csv")